Implement dots in context date page calendar menu
anyproto/anytype-ts pull request #1077
Opened 2024-11-28 16:52 UTC by Nek

---

- [ ] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### Description

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Related Tickets & Documents

### Mobile & Desktop Screenshots/Recordings

### Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [ ] 🙅 no documentation needed

### [optional] Are there any post-deployment tasks we need to perform?

2024-11-28 17:48 UTC, ra3orblade commented on src/ts/component/page/main/date.tsx
> +					return recDate.y == date.y && recDate.m == date.m && recDate.d == date.d;
Parts of logical statements should be wrapped in parenthesis. Also I didn't find declaration for `date` variable.
```
(recDate.y == date.y) && (recDate.m == date.m) && (recDate.d == date.d);
```

2024-11-29 11:22 UTC, Nek commented on src/ts/component/menu/dataview/calendar.tsx
> +									{check && <div className="bullet" /> }
Why? It's normal for React to write `check && <something />` as it ignores false values by design.

2024-11-29 14:30 UTC, ra3orblade requested changes

2024-11-29 14:30 UTC, ra3orblade commented on src/ts/component/menu/dataview/calendar.tsx
> +	}
Add semicolon.

2024-11-29 14:30 UTC, ra3orblade commented on src/ts/component/menu/dataview/calendar.tsx
> +}
Add semicolon.

2024-11-29 14:30 UTC, ra3orblade commented on src/ts/component/menu/dataview/calendar.tsx
> +									{check && <div className="bullet" /> }
It's normal but much harder to read.

2024-11-29 14:30 UTC, ra3orblade commented on src/ts/component/page/main/date.tsx
> +		}
Add semicolon.

2024-11-29 14:30 UTC, ra3orblade commented on src/ts/component/page/main/date.tsx
> +	getDotMap = (data: {d: number, m: number, y: number}[], callback: (res: Map<string, boolean>) => void): void => {
callback everywhere is written in camelCase, `callBack`

2024-12-02 14:32 UTC, ra3orblade approved these changes

2024-12-02 14:32 UTC, merged