Bilibili embed iframe
anyproto/anytype-ts pull request #517
Opened 2024-01-24 14:35 UTC by LavaCxx

---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### Description
I forgot to support the original iframe string.

### What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Related Tickets & Documents

### Mobile & Desktop Screenshots/Recordings

<img width="565" alt="image" src="https://github.com/anyproto/anytype-ts/assets/48022591/e7e7716d-f700-4504-ab0d-2ead0924d210">

### Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [x] 🙅 no documentation needed

### [optional] Are there any post-deployment tasks we need to perform?

2024-01-24 17:00 UTC, ra3orblade requested changes

2024-01-24 17:00 UTC, ra3orblade commented on src/ts/lib/util/embed.ts
> +					return;
return is incorrect here, break

2024-01-24 17:01 UTC, ra3orblade commented
Could you please explain what are you doing here? Embed url only checks url, not the source html code.

2024-01-25 02:14 UTC, LavaCxx commented
> Could you please explain what are you doing here? Embed url only checks url, not the source html code.

Sorry, I have already re-reviewed the code and modified the logic.

2024-01-25 09:41 UTC, ra3orblade commented
> > Could you please explain what are you doing here? Embed url only checks url, not the source html code.
> 
> Sorry, I have already re-reviewed the code and modified the logic.

Update from main pls, there is already logic for Bilibili to parse schemeless urls `// Fix Bilibili schemeless urls
					if (block.isEmbedBilibili() && text.match(/src="\/\/player[^"]+"/)) {
						text = text.replace(/src="(\/\/player[^"]+)"/, 'src="https:$1"');
					};`

Could you please combine these two logics under one `if` statement?

2024-01-25 10:30 UTC, ra3orblade commented
Something is wrong with your branch.

2024-01-25 11:29 UTC, LavaCxx commented
> Something is wrong with your branch, conflicts and shows changes that are already in main.

I'm not very good at solving git issues, maybe I should create a new pr.

2024-01-25 12:20 UTC, closed without merging